[package]
name = "mylife"
version = "0.1.0"
authors = ["Martin Schiller <hello@waozi.xyz>"]
edition = "2021"


[package.metadata.dioxus]
[package.metadata.dioxus.web]
asset-dir = "assets"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
once_cell = "1.17.1"
dioxus-logger = "0.5.1"
log = "0.4.6"
manganis = "0.2.2" 
futures-util = "0.3"
chrono = "0.4"
cfg-if = "1.0"
uuid = { version = "1.4", features = ["v4", "serde"] }
getrandom = { version = "0.2", features = ["js"] }
rfd = "0.14.1"
brotli = "3.4"
base64 = "0.21.0"
gloo-timers = "0.3.0"
usvg = "0.43.0"
resvg = "0.43.0"
tiny-skia = "0.11.4"
image = { version = "0.24", features = ["webp", "png", "webp-encoder"] }
webp = "0.3"
rand = "0.8.5"
rusttype = "0.9.3"
imageproc = "0.25.0"
hex_color = "3.0.0"


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus = { version = "0.5", features = ["desktop", "router"] }
tokio = { version = "1.0", features = ["time"] }
open = "1.7"
screenshots = "0.8.10"
dioxus-desktop = "0.5.6"
gtk = "0.18"
dioxus-ssr = { version = "0.5.6" }


[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus = { version = "0.5", features = ["web", "router"] }
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"
futures-channel = "0.3"
web-sys = { version = "0.3", features = ["ResizeObserver", "ResizeObserverEntry", "Window", "Navigator", "CanvasRenderingContext2d", "HtmlImageElement", "HtmlCanvasElement", "Element", "SvgElement"] }
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
js-sys = "0.3.4"
