[package]
name = "mylife"
version = "0.1.0"
authors = ["Martin Schiller <hello@waozi.xyz>"]
edition = "2021"


[package.metadata.dioxus]
[package.metadata.dioxus.web]
asset-dir = "assets"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
once_cell = "1.17.1"
dioxus-logger = "0.5.1"
log = "0.4.6"
manganis = "0.2.2" 
futures-util = "0.3"
chrono = "0.4"
cfg-if = "1.0"
uuid = { version = "1.4", features = ["v4", "serde"] }
getrandom = { version = "0.2", features = ["js"] }
rfd = "0.14.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus = { version = "0.5", features = ["desktop", "router"] }
tokio = { version = "1.0", features = ["time"] }
open = "1.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus = { version = "0.5", features = ["web", "router"] }
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"
futures-channel = "0.3"
web-sys = { version = "0.3", features = ["Window"] }
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
js-sys = "0.3.4"
