name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Add Cargo bin to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install latest dioxus-cli
        run: |
          nix develop --command bash -c '
            cargo install --force dioxus-cli
          '

      - name: Install wasm-bindgen-cli
        run: |
          nix develop --command bash -c '
            cargo install --force wasm-bindgen-cli
          '

      - name: Build with Nix
        run: |
          nix develop --command bash -c '
            dx build --release --platform web
          '

      - name: Cache Dioxus build artifacts
        uses: actions/cache@v3
        with:
          path: |
            target
            dist
          key: ${{ runner.os }}-dioxus-web-${{ hashFiles('**/Cargo.lock', '**/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-dioxus-web-

      - name: Create CNAME file
        run: echo "mylife.waozi.xyz" > dist/CNAME
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true