name: Github Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebp-dev libclang-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      
      - name: Install Dioxus CLI
        run: cargo install dioxus-cli
      
      - name: Build
        run: dx build --release --platform web
        env:
          PUBLIC_URL: "https://mylife.waozi.xyz"
      
      - name: Create CNAME file
        run: echo "mylife.waozi.xyz" > dist/CNAME
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true