name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        run: |
          sh <(curl -L https://nixos.org/nix/install) --no-daemon
          echo ". /home/runner/.nix-profile/etc/profile.d/nix.sh" >> ~/.bashrc
          . /home/runner/.nix-profile/etc/profile.d/nix.sh # Ensure Nix is in the PATH

      - name: Install Nix dependencies
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh # Ensure Nix is in the PATH
          nix-env -iA nixpkgs.cachix

      - name: Install Devenv
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh # Ensure Nix is in the PATH
          nix-env -iA nixpkgs.devenv

      - name: Build with Devenv
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh # Ensure Nix is in the PATH
          devenv run 'dx build --release --platform web'

      - name: Create CNAME file
        run: echo "mylife.waozi.xyz" > dist/CNAME
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true
